POST http://localhost:1338/login
Content-Type: application/json

{"username":"Aiden","password":"123456"}


### delet
DELETE http://localhost:1338/stockPicTag/deleteById/1


### delet
GET  http://localhost:1338/stock/myGroup/grouplist
### delet
POST http://localhost:8080/user/login
### delet
GET http://localhost:10100/stockBaseInfo/search?search=美利云

### delet
GET http://localhost:1338/stock/search?search=美利云
