server:
  port: 10100   #  配置启动端口号

spring: #springboot的配置
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&serverTimezone=Asia/Shanghai&serverTimezone=GMT%2B8&useSSL=FALSE
          username: root
          password: root
          type: com.zaxxer.hikari.HikariDataSource
          pool-name: MysqlDruidCP        #连接池名
          hikari:
            minimum-idle: 5                 #最小连接
            maximum-pool-size: 15        #最大连接
            is-auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
            idle-timeout: 30000        #最大空闲时常
            max-lifetime: 1800000        #最大生命周期
            connection-timeout: 30000        #连接超时时间
        slave:
#          driver-class-name: com.taosdata.jdbc.TSDBDriver
          url: jdbc:TAOS-RS://localhost:6041?user=root&password=taosdata
          username: root
          password: taosdata
          type: com.zaxxer.hikari.HikariDataSource
          pool-name: Data_trans_HikariCP
          hikari:
            minimum-idle: 10 #最小空闲连接数量
            idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
            maximum-pool-size: 100 #连接池最大连接数，默认是10
            is-auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
            max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
            connection-test-query: SELECT 1

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/**/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl